# ai-generated: 100% - Generated by Gemini, test runner script for L1-STRETCH-3
import pytest
import sys

class ResultsCollector:
    def __init__(self):
        self.passed = 0
        self.failed = 0

    def pytest_runtest_logreport(self, report):
        if report.when == "call":
            if report.passed:
                self.passed += 1
            elif report.failed:
                self.failed += 1

if __name__ == "__main__":
    collector = ResultsCollector()
    exit_code = pytest.main(["-q", "tests/test_svcdesk.py"], plugins=[collector])
    print(f"ITSMLAB-TESTS: passed={collector.passed} failed={collector.failed}")
    sys.exit(exit_code)