# ai-generated: 100% - Generated by Gemini, pytest suite for L1-STRETCH-3
import sys
import os

# Ensure project root is in Python path inside the container
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from fastapi.testclient import TestClient
from src.main import app

client = TestClient(app)

def test_01_health():
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}

def test_02_create_ticket_basic():
    payload = {
        "title": "Test Ticket 1",
        "impact": 1,
        "urgency": 1,
        "reporter": {"vip": False, "name": "Alice"}
    }
    res = client.post("/tickets", json=payload)
    assert res.status_code == 201
    data = res.json()
    assert data["priority"] == "P1"
    assert data["state"] == "new"

def test_03_create_ticket_p4():
    payload = {
        "title": "Test Ticket P4",
        "impact": 3,
        "urgency": 3,
        "reporter": {"vip": False, "name": "Bob"}
    }
    res = client.post("/tickets", json=payload)
    assert res.status_code == 201
    assert res.json()["priority"] == "P4"

def test_04_vip_elevation():
    payload = {
        "title": "VIP Ticket",
        "impact": 3,
        "urgency": 3,
        "reporter": {"vip": True, "name": "VIP User"}
    }
    res = client.post("/tickets", json=payload)
    assert res.status_code == 201
    assert res.json()["priority"] == "P2"

def test_05_list_tickets():
    res = client.get("/tickets")
    assert res.status_code == 200
    assert isinstance(res.json(), list)

def test_06_get_ticket_by_id():
    payload = {
        "title": "Get By ID",
        "impact": 2,
        "urgency": 2,
        "reporter": {"vip": False}
    }
    create_res = client.post("/tickets", json=payload)
    t_id = create_res.json()["id"]
    
    res = client.get(f"/tickets/{t_id}")
    assert res.status_code == 200
    assert res.json()["id"] == t_id

def test_07_ack_transition():
    payload = {"title": "Ack Test", "impact": 2, "urgency": 2, "reporter": {}}
    t_id = client.post("/tickets", json=payload).json()["id"]
    
    res = client.post(f"/tickets/{t_id}/ack")
    assert res.status_code == 200
    assert res.json()["state"] == "acknowledged"

def test_08_start_transition():
    payload = {"title": "Start Test", "impact": 2, "urgency": 2, "reporter": {}}
    t_id = client.post("/tickets", json=payload).json()["id"]
    client.post(f"/tickets/{t_id}/ack")
    
    res = client.post(f"/tickets/{t_id}/start")
    assert res.status_code == 200
    assert res.json()["state"] == "in_progress"

def test_09_resolve_transition():
    payload = {"title": "Resolve Test", "impact": 2, "urgency": 2, "reporter": {}}
    t_id = client.post("/tickets", json=payload).json()["id"]
    client.post(f"/tickets/{t_id}/ack")
    client.post(f"/tickets/{t_id}/start")
    
    res = client.post(f"/tickets/{t_id}/resolve")
    assert res.status_code == 200
    assert res.json()["state"] == "resolved"

def test_10_close_transition():
    payload = {"title": "Close Test", "impact": 2, "urgency": 2, "reporter": {}}
    t_id = client.post("/tickets", json=payload).json()["id"]
    client.post(f"/tickets/{t_id}/ack")
    client.post(f"/tickets/{t_id}/start")
    client.post(f"/tickets/{t_id}/resolve")
    
    res = client.post(f"/tickets/{t_id}/close")
    assert res.status_code == 200
    assert res.json()["state"] == "closed"

def test_11_immutable_closed_ticket():
    payload = {"title": "Immutable Test", "impact": 2, "urgency": 2, "reporter": {}}
    t_id = client.post("/tickets", json=payload).json()["id"]
    client.post(f"/tickets/{t_id}/ack")
    client.post(f"/tickets/{t_id}/start")
    client.post(f"/tickets/{t_id}/resolve")
    client.post(f"/tickets/{t_id}/close")
    
    res = client.post(f"/tickets/{t_id}/reopen")
    assert res.status_code == 409