# ai-generated: 100% - Generated by Gemini, L1 SLA + L2 DORA metrics implementation
from datetime import datetime, timedelta, timezone
from decimal import Decimal, ROUND_HALF_UP
from zoneinfo import ZoneInfo
from typing import Optional, List, Dict, Any
from fastapi import FastAPI, HTTPException, Request, Header
from fastapi.responses import JSONResponse
from fastapi.exceptions import RequestValidationError
from pydantic import BaseModel, Field
import uuid

app = FastAPI(title="svcdesk API")

@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    return JSONResponse(status_code=422, content={"error": exc.errors()})

@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"error": {"message": exc.detail}})

tickets_db = {}
WARSAW = ZoneInfo("Europe/Warsaw")

# --- L1 SVCDESK MODELS & HELPERS ---
class Reporter(BaseModel):
    vip: bool = False
    name: str = "Unknown"

class TicketCreate(BaseModel):
    title: str = Field(..., max_length=200)
    description: str = ""
    impact: int = Field(..., ge=1, le=3)
    urgency: int = Field(..., ge=1, le=3)
    reporter: Reporter

def get_current_time(clock_header: Optional[str]) -> str:
    if clock_header:
        try:
            datetime.fromisoformat(clock_header.replace('Z', '+00:00'))
            return clock_header
        except ValueError:
            raise HTTPException(status_code=400, detail="Invalid X-Test-Clock format")
    return datetime.now(timezone.utc).isoformat()

def is_business_hours(dt: datetime) -> bool:
    dt_local = dt.astimezone(WARSAW)
    return dt_local.weekday() < 5 and 8 <= dt_local.hour < 16

def add_business_hours(start_dt: datetime, hours: float) -> datetime:
    dt = start_dt.astimezone(WARSAW)
    remaining_seconds = hours * 3600

    while remaining_seconds > 0:
        if dt.weekday() >= 5:
            days_ahead = 7 - dt.weekday()
            dt = dt.replace(hour=8, minute=0, second=0, microsecond=0) + timedelta(days=days_ahead)
            continue
        if dt.hour < 8:
            dt = dt.replace(hour=8, minute=0, second=0, microsecond=0)
            continue
        if dt.hour >= 16:
            days_ahead = 1 if dt.weekday() < 4 else 3
            dt = dt.replace(hour=8, minute=0, second=0, microsecond=0) + timedelta(days=days_ahead)
            continue

        end_of_day = dt.replace(hour=16, minute=0, second=0, microsecond=0)
        seconds_to_eod = (end_of_day - dt).total_seconds()

        if remaining_seconds <= seconds_to_eod:
            dt += timedelta(seconds=remaining_seconds)
            remaining_seconds = 0
        else:
            dt = end_of_day
            remaining_seconds -= seconds_to_eod

    return dt.astimezone(timezone.utc)

def calculate_sla(created_at: str, priority: str) -> dict:
    dt_created = datetime.fromisoformat(created_at.replace('Z', '+00:00'))
    sla_matrix = {
        "P1": (0.25, 4.0),
        "P2": (1.0, 8.0),
        "P3": (4.0, 24.0),
        "P4": (8.0, 72.0)
    }
    ack_hrs, resolve_hrs = sla_matrix.get(priority, (8.0, 72.0))
    ack_due = add_business_hours(dt_created, ack_hrs)
    resolve_due = add_business_hours(dt_created, resolve_hrs)
    close_due = resolve_due + timedelta(days=7) 
    return {
        "ack_due_at": ack_due.isoformat().replace('+00:00', 'Z'),
        "resolve_due_at": resolve_due.isoformat().replace('+00:00', 'Z'),
        "close_due_at": close_due.isoformat().replace('+00:00', 'Z')
    }

# --- L2 DORA HELPERS & MATH ---
def parse_iso(dt_str: str) -> datetime:
    if dt_str.endswith("Z"):
        dt_str = dt_str[:-1] + "+00:00"
    return datetime.fromisoformat(dt_str).astimezone(timezone.utc)

def round_half_up(val: float, decimals: int = 0):
    if val is None:
        return None
    d = Decimal(str(val))
    if decimals == 0:
        return int(d.quantize(Decimal('1'), rounding=ROUND_HALF_UP))
    else:
        q = Decimal('10') ** -decimals
        return float(d.quantize(q, rounding=ROUND_HALF_UP))

def compute_median(values: List[float]) -> Optional[int]:
    if not values:
        return None
    s = sorted(values)
    n = len(s)
    if n % 2 == 1:
        med = float(s[n // 2])
    else:
        med = float(s[n // 2 - 1] + s[n // 2]) / 2.0
    return round_half_up(med, 0)

# --- L1 TICKETS ENDPOINTS ---
@app.get("/health")
def health_check():
    return {"status": "ok"}

@app.post("/tickets", status_code=201)
def create_ticket(ticket: TicketCreate, x_test_clock: Optional[str] = Header(None, alias="X-Test-Clock")):
    ticket_id = str(uuid.uuid4())
    created_at = get_current_time(x_test_clock)
    matrix = {
        (1, 1): "P1", (1, 2): "P2", (1, 3): "P3",
        (2, 1): "P2", (2, 2): "P3", (2, 3): "P4",
        (3, 1): "P3", (3, 2): "P4", (3, 3): "P4",
    }
    base_priority = matrix.get((ticket.impact, ticket.urgency), "P4")
    final_priority = base_priority
    if ticket.reporter.vip and base_priority in ["P3", "P4"]:
        final_priority = "P2"
        
    new_ticket = {
        "id": ticket_id,
        "title": ticket.title,
        "state": "new",
        "priority": final_priority,
        "created_at": created_at,
        "reporter": ticket.reporter.model_dump(),
        "sla": calculate_sla(created_at, final_priority)
    }
    tickets_db[ticket_id] = new_ticket
    return new_ticket

@app.get("/tickets")
def list_tickets(state: Optional[str] = None, priority: Optional[str] = None):
    results = list(tickets_db.values())
    if state:
        results = [t for t in results if t["state"] == state]
    if priority:
        results = [t for t in results if t["priority"] == priority]
    return results

@app.get("/tickets/{ticket_id}")
def get_ticket(ticket_id: str):
    if ticket_id not in tickets_db:
        raise HTTPException(status_code=404, detail="Ticket not found")
    return tickets_db[ticket_id]

@app.post("/tickets/{ticket_id}/{action}", status_code=200)
def transition_ticket(ticket_id: str, action: str, x_test_clock: Optional[str] = Header(None, alias="X-Test-Clock")):
    if ticket_id not in tickets_db:
        raise HTTPException(status_code=404, detail="Not Found")
    
    ticket = tickets_db[ticket_id]
    current_state = ticket["state"]
    current_time = get_current_time(x_test_clock)
    
    if action == "ack":
        if current_state != "new": raise HTTPException(status_code=409, detail="Conflict")
        ticket["state"] = "acknowledged"
        ticket["acknowledged_at"] = current_time
    elif action == "start":
        if current_state != "acknowledged": raise HTTPException(status_code=409, detail="Conflict")
        ticket["state"] = "in_progress"
        ticket["started_at"] = current_time
    elif action == "resolve":
        if current_state != "in_progress": raise HTTPException(status_code=409, detail="Conflict")
        ticket["state"] = "resolved"
        ticket["resolved_at"] = current_time
    elif action == "close":
        if current_state != "resolved": raise HTTPException(status_code=409, detail="Conflict")
        ticket["state"] = "closed"
        ticket["closed_at"] = current_time
    elif action == "reopen":
        if current_state == "closed": raise HTTPException(status_code=409, detail="Ticket is immutable (C2)")
        if current_state != "resolved": raise HTTPException(status_code=409, detail="Conflict")
        resolved_at = datetime.fromisoformat(ticket["resolved_at"].replace('Z', '+00:00'))
        now = datetime.fromisoformat(current_time.replace('Z', '+00:00'))
        if (now - resolved_at).total_seconds() > 7 * 86400:
            raise HTTPException(status_code=409, detail="Reopen window expired")
        ticket["state"] = "in_progress"
    else:
        raise HTTPException(status_code=404, detail="Invalid action")
    return ticket

@app.get("/tickets/{ticket_id}/sla")
def get_sla(ticket_id: str, x_test_clock: Optional[str] = Header(None, alias="X-Test-Clock")):
    if ticket_id not in tickets_db:
        raise HTTPException(status_code=404, detail="Not Found")
    ticket = tickets_db[ticket_id]
    current_time = get_current_time(x_test_clock)
    dt_now = datetime.fromisoformat(current_time.replace('Z', '+00:00'))
    ack_due = datetime.fromisoformat(ticket["sla"]["ack_due_at"].replace('Z', '+00:00'))
    resolve_due = datetime.fromisoformat(ticket["sla"]["resolve_due_at"].replace('Z', '+00:00'))
    ack_breached = dt_now > ack_due if not ticket.get("acknowledged_at") else datetime.fromisoformat(ticket["acknowledged_at"].replace('Z', '+00:00')) > ack_due
    resolve_breached = dt_now > resolve_due if not ticket.get("resolved_at") else datetime.fromisoformat(ticket["resolved_at"].replace('Z', '+00:00')) > resolve_due
    return {"ack_breached": ack_breached, "resolve_breached": resolve_breached, "paused": not is_business_hours(dt_now)}

# --- L2 DORA ENDPOINTS ---
@app.get("/dora/ticket-events")
def get_ticket_events():
    events = []
    phase_to_state = {"created": "new", "acknowledged": "acknowledged", "resolved": "resolved", "closed": "closed"}
    for tid, ticket in tickets_db.items():
        priority = ticket.get("priority", "P4")
        timestamps = [
            ("created", ticket.get("created_at")),
            ("acknowledged", ticket.get("acknowledged_at")),
            ("resolved", ticket.get("resolved_at")),
            ("closed", ticket.get("closed_at"))
        ]
        for phase, ts in timestamps:
            if ts:
                events.append({
                    "ticket_id": tid,
                    "at": ts,
                    "phase": phase,
                    "priority": priority,
                    "state": phase_to_state[phase]
                })
    events.sort(key=lambda x: (x["at"], x["ticket_id"]))
    return events

@app.post("/dora/metrics")
def calculate_dora_metrics(payload: Dict[str, Any]):
    if not isinstance(payload, dict) or "window" not in payload or not isinstance(payload["window"], dict):
        raise HTTPException(status_code=422, detail="Missing or invalid window")
    win = payload["window"]
    if "from" not in win or "to" not in win:
        raise HTTPException(status_code=422, detail="Window missing from/to")
    try:
        dt_from = parse_iso(win["from"])
        dt_to = parse_iso(win["to"])
    except Exception:
        raise HTTPException(status_code=422, detail="Invalid window timestamp")
    if dt_to <= dt_from:
        raise HTTPException(status_code=422, detail="Window to <= from")
    if "events" not in payload or not isinstance(payload["events"], list):
        raise HTTPException(status_code=422, detail="Missing or invalid events array")

    raw_events = payload["events"]

    # R-05 Deduplication by event_id
    seen_ids = set()
    events = []
    for ev in raw_events:
        eid = ev.get("event_id") or (ev.get("type"), ev.get("sha"), ev.get("at"))
        if eid not in seen_ids:
            seen_ids.add(eid)
            events.append(ev)

    # Well-formedness checks (R-06 & section 1)
    known_shas = {ev["sha"] for ev in events if ev.get("type") == "commit" and "sha" in ev}
    known_incidents = {ev["incident_id"] for ev in events if ev.get("type") == "incident" and "incident_id" in ev}
    known_deployments = {ev["deployment_id"] for ev in events if ev.get("type") == "deployment" and "deployment_id" in ev}

    for ev in events:
        if ev.get("type") == "commit":
            reverts = ev.get("reverts")
            change_id = ev.get("change_id")
            if reverts is not None:
                if change_id is not None or reverts not in known_shas:
                    raise HTTPException(status_code=422, detail=f"Malformed revert commit {ev}")
            else:
                if change_id is None:
                    raise HTTPException(status_code=422, detail=f"Malformed commit missing change_id {ev}")
        elif ev.get("type") == "deployment":
            for c_sha in ev.get("commits", []):
                if c_sha not in known_shas:
                    raise HTTPException(status_code=422, detail=f"Deployment commit {c_sha} unknown")
            caused_by = ev.get("caused_by")
            if caused_by is not None and caused_by not in known_incidents:
                raise HTTPException(status_code=422, detail=f"Deployment caused_by {caused_by} unknown")
        elif ev.get("type") == "incident":
            for d_id in ev.get("deployments", []):
                if d_id not in known_deployments:
                    raise HTTPException(status_code=422, detail=f"Incident deployment {d_id} unknown")

    commits_by_sha = {ev["sha"]: ev for ev in events if ev.get("type") == "commit"}

    # R-06 Change Identity
    change_id_map = {}
    revert_chains_collapsed = 0
    for sha, c_ev in commits_by_sha.items():
        if c_ev.get("reverts"):
            revert_chains_collapsed += 1
            curr = c_ev
            visited = {sha}
            while curr.get("reverts"):
                rev_sha = curr.get("reverts")
                if rev_sha in visited or rev_sha not in commits_by_sha:
                    break
                visited.add(rev_sha)
                curr = commits_by_sha[rev_sha]
            change_id_map[sha] = curr.get("change_id")
        else:
            change_id_map[sha] = c_ev.get("change_id")

    all_changes = set(cid for cid in change_id_map.values() if cid is not None)

    # R-07 First commit instant
    change_first_commit_at = {}
    for sha, c_ev in commits_by_sha.items():
        cid = change_id_map.get(sha)
        if cid:
            c_at = parse_iso(c_ev["at"])
            if cid not in change_first_commit_at or c_at < change_first_commit_at[cid]:
                change_first_commit_at[cid] = c_at

    # R-01 & R-02 Production deployments in window
    deployments_in_window = []
    deployments_without_commits = 0
    for ev in events:
        if ev.get("type") == "deployment" and ev.get("environment") == "production":
            d_at = parse_iso(ev["at"])
            if dt_from <= d_at < dt_to:
                deployments_in_window.append(ev)
                if not ev.get("commits"):
                    deployments_without_commits += 1

    # E3 commits_never_on_main
    commits_never_on_main_shas = set()
    for d in deployments_in_window:
        for sha in d.get("commits", []):
            if sha in commits_by_sha and commits_by_sha[sha].get("branch") != "main":
                commits_never_on_main_shas.add(sha)

    # R-08 Lead time pairs
    deployed_shas_seen = set()
    lead_time_pairs_values = []
    negative_lead_time_pairs = 0
    deployments_in_window_sorted = sorted(deployments_in_window, key=lambda x: parse_iso(x["at"]))

    for d in deployments_in_window_sorted:
        d_at = parse_iso(d["at"])
        if d.get("outcome") == "success":
            for sha in d.get("commits", []):
                if sha not in deployed_shas_seen:
                    deployed_shas_seen.add(sha)
                    if sha in commits_by_sha:
                        c_at = parse_iso(commits_by_sha[sha]["at"])
                        lt_sec = (d_at - c_at).total_seconds()
                        if lt_sec < 0:
                            negative_lead_time_pairs += 1
                            lt_sec = 0.0
                        lead_time_pairs_values.append(lt_sec)

    change_lead_time_seconds_p50 = compute_median(lead_time_pairs_values)

    # R-11 Deployment frequency
    window_days = (dt_to - dt_from).total_seconds() / 86400.0
    total_deployments = len(deployments_in_window)
    df_per_day = round_half_up(total_deployments / window_days, 6) if window_days > 0 else 0.0

    successful_deployments = [d for d in deployments_in_window if d.get("outcome") == "success"]
    failed_deployments = [d for d in deployments_in_window if d.get("outcome") == "failure"]

    # R-14 CFR & R-15 DRR
    cfr = round_half_up(len(failed_deployments) / total_deployments, 6) if total_deployments > 0 else None
    rework_deps = [d for d in deployments_in_window if d.get("unplanned") is True and d.get("caused_by") is not None]
    drr = round_half_up(len(rework_deps) / total_deployments, 6) if total_deployments > 0 else None

    # R-12 & R-13 Incidents & Recovery
    incidents_by_id = {}
    for ev in events:
        if ev.get("type") == "incident":
            iid = ev["incident_id"]
            if iid not in incidents_by_id:
                incidents_by_id[iid] = {"opened": None, "resolved": None, "deployments": []}
            p = ev.get("phase")
            if p == "opened":
                incidents_by_id[iid]["opened"] = parse_iso(ev["at"])
                incidents_by_id[iid]["deployments"] = ev.get("deployments", [])
            elif p == "resolved":
                incidents_by_id[iid]["resolved"] = parse_iso(ev["at"])

    # E6 overlapping
    inc_list = list(incidents_by_id.items())
    overlapping_pairs = 0
    for i in range(len(inc_list)):
        o1 = inc_list[i][1]["opened"]
        if o1 is None: continue
        r1 = inc_list[i][1]["resolved"] if inc_list[i][1]["resolved"] is not None else dt_to
        for j in range(i + 1, len(inc_list)):
            o2 = inc_list[j][1]["opened"]
            if o2 is None: continue
            r2 = inc_list[j][1]["resolved"] if inc_list[j][1]["resolved"] is not None else dt_to
            if o1 < r2 and o2 < r1:
                overlapping_pairs += 1

    recovery_times = []
    recovered_failures_count = 0
    open_failures_count = 0

    for fd in failed_deployments:
        dep_id = fd["deployment_id"]
        d_at = parse_iso(fd["at"])
        candidates = []
        for iid, inc in incidents_by_id.items():
            if dep_id in inc["deployments"] and inc["opened"] is not None:
                candidates.append((inc["opened"], iid, inc))
        if candidates:
            candidates.sort(key=lambda x: (x[0], x[1]))
            covering_inc = candidates[0][2]
            if covering_inc["resolved"] is not None:
                recovered_failures_count += 1
                rec_sec = max(0.0, (covering_inc["resolved"] - d_at).total_seconds())
                recovery_times.append(rec_sec)
            else:
                open_failures_count += 1
        else:
            open_failures_count += 1

    fdrt_p50 = compute_median(recovery_times)

    # R-16 & R-17 Ground truth
    changes_delivered_map = {}
    for d in deployments_in_window_sorted:
        if d.get("outcome") == "success":
            d_at = parse_iso(d["at"])
            for sha in d.get("commits", []):
                cid = change_id_map.get(sha)
                if cid and (cid not in changes_delivered_map or d_at < changes_delivered_map[cid]):
                    changes_delivered_map[cid] = d_at

    true_lead_times = [
        max(0.0, (first_dep_at - change_first_commit_at[cid]).total_seconds())
        for cid, first_dep_at in changes_delivered_map.items()
    ]
    true_clt_p50 = compute_median(true_lead_times)

    return {
        "spec_version": "1.0.0",
        "window": {"from": win["from"], "to": win["to"]},
        "deployment_frequency_per_day": df_per_day,
        "change_lead_time_seconds_p50": change_lead_time_seconds_p50,
        "failed_deployment_recovery_time_seconds_p50": fdrt_p50,
        "change_fail_rate": cfr,
        "deployment_rework_rate": drr,
        "counts": {
            "deployments": total_deployments,
            "successful_deployments": len(successful_deployments),
            "failed_deployments": len(failed_deployments),
            "recovered_failures": recovered_failures_count,
            "open_failures": open_failures_count,
            "rework_deployments": len(rework_deps),
            "lead_time_pairs": len(lead_time_pairs_values),
            "changes": len(all_changes)
        },
        "anomalies": {
            "negative_lead_time_pairs": negative_lead_time_pairs,
            "deployments_without_commits": deployments_without_commits,
            "commits_never_on_main": len(commits_never_on_main_shas),
            "revert_chains_collapsed": revert_chains_collapsed,
            "overlapping_incident_pairs": overlapping_pairs
        },
        "ground_truth": {
            "changes_delivered": len(changes_delivered_map),
            "true_change_lead_time_seconds_p50": true_clt_p50
        }
    }