# ai-generated: 100% - Generated by Gemini for Stretch 1 rework classification feature

def is_rework_deployment(deployment: dict) -> bool:
    """Classifies whether a deployment represents rework based on unplanned flag and caused_by incident."""
    unplanned = deployment.get("unplanned", False)
    caused_by = deployment.get("caused_by")
    return bool(unplanned and caused_by)